# Generated by Django 5.1.5 on 2025-03-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_option_question_option_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='quest',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='blog.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='blog.option'),
        ),
    ]
