# Generated by Django 5.1.5 on 2025-03-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Quiz',
        ),
    ]
