# Generated by Django 5.1.5 on 2025-03-17 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_quiz_users_who_attempted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='users_who_attempted',
        ),
        migrations.AddField(
            model_name='quiz',
            name='users_who_attempted',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
