# Generated by Django 5.2 on 2025-05-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_userscore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='portfolio')),
                ('technologies_used', models.CharField(max_length=500)),
                ('links', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='users_who_attempted',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
