# Generated by Django 5.2 on 2025-05-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_project_remove_option_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
