# Generated by Django 5.2 on 2025-05-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_project_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='image',
        ),
    ]
