# Generated by Django 5.2 on 2025-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_images_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'unread'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='unread')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
