# Generated by Django 5.2 on 2025-05-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_clientmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmessage',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='clientmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='unread', max_length=12),
        ),
    ]
