# Generated by Django 5.2 on 2025-11-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='socials',
        ),
    ]
